title: lgc-gn
description: Portfolio and project showcase
baseurl: ""
url: "https://lgc-gn.github.io"

theme: minima

minima:
  skin: dark
  social_links:
    - {platform: github, user_url:"https://github.com/lgc-gn"}

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.html

sass:
  quiet_deps: true

head_scripts:
  - /assets/css/default.css