title: lgc-gn
description: Portfolio and project showcase
baseurl: ""
url: "https://lgc-gn.github.io"

remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.html
